services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel_installer_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
