"""
The README generated by ``GET /v2/new-inertia`` (``README.inertia-v2.md.j2``).

It has to render for every combination of the options that change it, as well-formed Markdown
(balanced code fences, tables GitHub renders as tables, links that point at a heading), and
what it says about the project has to match the project: the Stack table lists the services the
Compose files define, the variable table the ``${VAR}`` placeholders of the staging/production
stacks, and the minimal env file it shows is exactly what those stacks need. The last two are
checked with the real ``docker compose config`` (skipped when the Compose plugin is not
installed); ``_run`` is replaced by a recorder, so no Composer, PHP or npm is needed.
"""

import io
import os
import re
import shutil
import subprocess
import zipfile

import pytest
import yaml
from fastapi.testclient import TestClient

from main import app
from services import installer_service
from services.installer_service import slugify_app_name

DBS = ["mysql", "postgres", "sqlite"]
# (queue, horizon): Horizon needs Redis, so it is only combined with it.
QUEUES = [("database", False), ("redis", False), ("redis", True), ("sync", False)]
PROXIES = [None, "proxy-net"]
CI_PROVIDERS = ["none", "github", "gitlab"]
STACKS = ["docker-compose.stage.yml", "docker-compose.prod.yml"]

# The options that only change the wording of the README, each tried on its own.
COSMETIC_VARIANTS = [
    {"starter_kit": kit} for kit in ("react", "vue", "livewire", "livewire-class-components")
] + [
    {"auth_provider": "workos"},
    {"teams": "true"},
    {"testing_framework": "pest"},
    {"install_boost": "true"},
    {"locale": "pt_BR"},
    {"max_upload_mb": "1024"},
    {"php_version": "8.2"},
    {"app_port": "9090"},
    {"auth_features": ["2fa", "passkeys"]},
    {"app_name": "Café & Co / Ünï | 100%"},
]


# The two files ``telescope=true`` patches, cut down to what the patch looks for.
APP_SERVICE_PROVIDER = """<?php

namespace App\\Providers;

use Illuminate\\Support\\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        //
    }
}
"""
PROVIDERS_PHP = """<?php

use App\\Providers\\AppServiceProvider;

return [
    AppServiceProvider::class,
];
"""


@pytest.fixture
def client(monkeypatch):
    def fake_run(cmd, *, cwd, env, timeout, check=True):
        if cmd[:2] == ["composer", "create-project"]:
            project = installer_service.Path(cwd) / cmd[3]
            (project / "app" / "Providers").mkdir(parents=True)
            (project / "bootstrap").mkdir()
            (project / "app" / "Providers" / "AppServiceProvider.php").write_text(APP_SERVICE_PROVIDER)
            (project / "bootstrap" / "providers.php").write_text(PROVIDERS_PHP)
            (project / ".env.example").write_text("APP_KEY=\n")
        elif cmd[:3] == ["php", "artisan", "key:generate"]:
            (installer_service.Path(cwd) / ".env").write_text("APP_KEY=base64:test\n")

    monkeypatch.setattr(installer_service, "_run", fake_run)
    monkeypatch.setattr(installer_service, "_build_env", lambda: {})
    return TestClient(app)


def _get_project(client: TestClient, **params) -> zipfile.ZipFile:
    response = client.get("/v2/new-inertia", params={"app_name": "demo", **params})
    assert response.status_code == 200, response.text
    return zipfile.ZipFile(io.BytesIO(response.content))


def _text(archive: zipfile.ZipFile, name: str) -> str:
    root = archive.namelist()[0].split("/")[0]  # the slugified app name
    return archive.read(f"{root}/{name}").decode()


def _combo(db, queue, horizon, proxy, ci="none", **extra) -> dict:
    params = {"db": db, "queue": queue, "horizon": str(horizon).lower(), "ci_provider": ci, **extra}
    if proxy:
        params["proxy_network"] = proxy
    return params


# ── A small Markdown reader: just what the checks below need ──────────────────


def _outside_fences(text: str):
    """Yield ``(line, in_fence)`` for every line; the fence lines themselves are ``in_fence``."""
    in_fence = False
    for line in text.splitlines():
        if line.startswith("```"):
            yield line, True
            in_fence = not in_fence
        else:
            yield line, in_fence


def _slug(heading: str) -> str:
    """GitHub's anchor for a heading."""
    return re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")


def _split_row(row: str) -> list[str]:
    """The cells of a table row. Like GitHub, only ``\\|`` keeps a pipe inside a cell."""
    assert row.startswith("|") and row.rstrip().endswith("|"), f"not a table row: {row!r}"
    return [cell.strip().replace("\\|", "|") for cell in re.split(r"(?<!\\)\|", row.strip())[1:-1]]


def _tables(text: str) -> list[list[list[str]]]:
    """Every table outside code fences, as a list of rows of cells (header and separator included)."""
    tables: list[list[list[str]]] = []
    current: list[list[str]] = []
    for line, in_fence in _outside_fences(text):
        if not in_fence and line.startswith("|"):
            current.append(_split_row(line))
        else:
            if current:
                tables.append(current)
            current = []
    if current:
        tables.append(current)
    return tables


def _section(text: str, heading: str) -> str:
    """The text under ``heading`` (e.g. ``"## Stack"``), up to the next heading of the same or a higher level."""
    level = len(heading.split()[0])
    collected: list[str] = []
    inside = False
    for line, in_fence in _outside_fences(text):
        found = None if in_fence else re.match(r"(#+) ", line)
        if found and inside and len(found.group(1)) <= level:
            break
        if line == heading and not in_fence:
            inside = True
        elif inside:
            collected.append(line)
    assert inside, f"no {heading!r} heading"
    return "\n".join(collected)


def _table_rows(text: str, heading: str) -> list[list[str]]:
    """The body rows of the first table under ``heading``."""
    return _tables(_section(text, heading))[0][2:]


def _assert_well_formed(readme: str) -> None:
    assert not re.search(r"\{\{|\{%|\{#|%\}|#\}", readme), "unrendered template syntax"
    fences = [line for line in readme.splitlines() if line.startswith("```")]
    assert len(fences) % 2 == 0, "unbalanced code fence"

    for table in _tables(readme):
        assert len(table) >= 2, f"table without a separator row: {table}"
        header, separator, *rows = table
        assert all(re.fullmatch(r":?-+:?", cell) for cell in separator), f"no separator row under {header}"
        for row in rows:
            assert len(row) == len(header), f"{len(row)} cells under a {len(header)}-column header: {row}"

    anchors = {
        _slug(match.group(2))
        for line, in_fence in _outside_fences(readme)
        if not in_fence and (match := re.match(r"(#+) (.+)", line))
    }
    for target in re.findall(r"\]\(#([^)]+)\)", readme):
        assert target in anchors, f"link to #{target}, which is not a heading"


# ── Renders for every combination ─────────────────────────────────────────────


@pytest.mark.parametrize("ci", CI_PROVIDERS)
@pytest.mark.parametrize("proxy", PROXIES)
@pytest.mark.parametrize("telescope", [False, True])
@pytest.mark.parametrize(("queue", "horizon"), QUEUES)
@pytest.mark.parametrize("db", DBS)
def test_readme_renders_for_every_option_combination(client, db, queue, horizon, telescope, proxy, ci):
    params = _combo(db, queue, horizon, proxy, ci, telescope=str(telescope).lower())
    readme = _text(_get_project(client, **params), "README.md")

    _assert_well_formed(readme)

    config = {row[0]: row[1] for row in _table_rows(readme, "## Project configuration")}
    assert config["Database"] == db
    assert config["Queue"] == queue
    assert ("Horizon" in config) == horizon
    assert ("Proxy network" in config) == bool(proxy)
    assert ("CI pipeline" in config) == (ci != "none")
    assert ("Laravel Telescope" in config) == telescope
    assert {"Locale", "Max upload size"} <= set(config)  # the options every project has


@pytest.mark.parametrize("variant", COSMETIC_VARIANTS, ids=lambda variant: next(iter(variant)))
def test_readme_renders_for_the_other_options_too(client, variant):
    for params in (variant, {**variant, "db": "sqlite", "queue": "sync", "telescope": "true"}):
        _assert_well_formed(_text(_get_project(client, **params), "README.md"))


def test_the_checker_catches_what_it_is_meant_to():
    # The README keeps failing these silently if the checks above go slack.
    good = "# T\n\n| a | b |\n|---|---|\n| 1 | 2 |\n\n[t](#t)\n"
    _assert_well_formed(good)
    for bad in (
        good.replace("(#t)", "(#nowhere)"),
        good.replace("| 1 | 2 |", "| 1 | 2 | 3 |"),
        good.replace("|---|---|\n", ""),
        good.replace("| 1 | 2 |\n", "| 1 | 2 |\n\n| 3 | 4 |\n"),
        good + "```\nopen\n",
        good + "{{ left }}\n",
        good.replace("| 1 | 2 |", "| `a|b` | 2 |"),
    ):
        with pytest.raises(AssertionError):
            _assert_well_formed(bad)


# ── The unzip example matches the archive ─────────────────────────────────────


@pytest.mark.parametrize("app_name", ["my-app", "My App", "Café & Co", "  Ünï/cödé  ", "!!!", "a b"])
def test_quick_start_uses_the_archive_and_folder_names(client, app_name):
    response = client.get("/v2/new-inertia", params={"app_name": app_name, "starter_kit": "vue"})
    assert response.status_code == 200, response.text
    archive = zipfile.ZipFile(io.BytesIO(response.content))
    readme = _text(archive, "README.md")
    slug = slugify_app_name(app_name)

    assert archive.namelist()[0].split("/")[0] == slug
    assert f'filename="laravel-{slug}-inertia-vue-docker.zip"' in response.headers["content-disposition"]
    assert f"unzip laravel-{slug}-inertia-vue-docker.zip\ncd {slug}\n" in readme


# ── The Stack table matches the Compose files ─────────────────────────────────


def _stack_rows(readme: str) -> dict[str, list[str]]:
    return {row[0]: row for row in _table_rows(readme, "## Stack")}


@pytest.mark.parametrize("proxy", PROXIES)
@pytest.mark.parametrize(("queue", "horizon"), QUEUES)
@pytest.mark.parametrize("db", DBS)
def test_stack_table_lists_exactly_the_services_of_the_compose_files(client, db, queue, horizon, proxy):
    archive = _get_project(client, **_combo(db, queue, horizon, proxy, php_version="8.3", app_port="9090"))
    rows = _stack_rows(_text(archive, "README.md"))
    dev, stage, prod = (yaml.safe_load(_text(archive, name))["services"] for name in ("docker-compose.yml", *STACKS))

    # Every service of the dev stack is a row and the other way round, ``vite`` being dev-only.
    assert set(rows) == set(dev)
    # A service is deployed (``yes``) exactly when both deploy stacks define it.
    assert set(stage) == set(prod)
    for name, (_, _, _, deployed) in rows.items():
        assert deployed.startswith("yes") == (name in stage), name
    assert set(stage) == set(dev) - {"vite"}


@pytest.mark.parametrize("db", DBS)
@pytest.mark.parametrize(("queue", "horizon"), QUEUES)
def test_stack_table_images_and_ports_are_the_ones_in_the_compose_files(client, db, queue, horizon):
    archive = _get_project(client, **_combo(db, queue, horizon, None, php_version="8.3", app_port="9090"))
    rows = _stack_rows(_text(archive, "README.md"))
    dev = yaml.safe_load(_text(archive, "docker-compose.yml"))["services"]
    dockerfile = _text(archive, "Dockerfile")

    for name, service in dev.items():
        _, image, dev_cell, _ = rows[name]
        ports = [str(port).split(":")[0] for port in service.get("ports", [])]
        # The dev column names every published host port, and says so only when there is one.
        assert all(port in dev_cell for port in ports), (name, ports, dev_cell)
        assert ("host port" in dev_cell) == bool(ports), (name, dev_cell)

        if "build" in service:
            assert dockerfile.startswith("FROM php:8.3-fpm-alpine\n")
            assert "php:8.3-fpm-alpine" in image
        elif name == "worker":
            assert service["image"] == dev["app"]["image"] and image == "same image as app"
        elif name == "vite":
            assert image.startswith(f"{service['image']},") and service["image"] == "php:8.3-cli-alpine"
            assert "apk add --no-cache nodejs npm" in service["command"]
        else:
            assert image == service["image"], name


def test_the_readme_no_longer_claims_a_node_image_or_an_unconditional_redis(client):
    for queue in ("database", "redis", "sync"):
        readme = _text(_get_project(client, queue=queue), "README.md")

        assert "node:20" not in readme and "Node 20" not in readme
        assert ("| redis |" in readme) == (queue == "redis")


# ── The variable table matches the staging/production stacks ──────────────────

LIMIT_VARIABLE = re.compile(r"(APP|WORKER|DB|REDIS)_(CPU|MEM)_(LIMIT|RESERVATION)")


def _placeholders(compose_text: str) -> tuple[set[str], set[str]]:
    """The variables a stack reads from the environment, and which of them are required (``:?``)."""
    # Comments are prose (the header says "the ${VAR} placeholders"), not placeholders.
    code = "\n".join(line for line in compose_text.splitlines() if not line.lstrip().startswith("#"))
    referenced = set(re.findall(r"\$\{([A-Z][A-Z0-9_]*)", code))
    required = set(re.findall(r"\$\{([A-Z][A-Z0-9_]*):\?", code))
    return referenced, required


@pytest.mark.parametrize("proxy", PROXIES)
@pytest.mark.parametrize(("queue", "horizon"), QUEUES)
@pytest.mark.parametrize("db", DBS)
def test_variable_table_lists_every_variable_of_the_deploy_stacks(client, db, queue, horizon, proxy):
    archive = _get_project(client, **_combo(db, queue, horizon, proxy))
    rows = _table_rows(_text(archive, "README.md"), "### Environment variables")
    documented = {name for row in rows for name in re.findall(r"`(<?[A-Z][A-Z0-9_<>]*)`", row[0])}
    documented_required = {name for row in rows if row[1] == "yes" for name in re.findall(r"`([A-Z_]+)`", row[0])}

    referenced, required = set(), set()
    for stack in STACKS:
        stack_referenced, stack_required = _placeholders(_text(archive, stack))
        referenced |= stack_referenced
        required |= stack_required
    # The four limit variables of each service are one row, written with a <PREFIX>.
    covered_by_the_limits_row = {name for name in referenced if LIMIT_VARIABLE.fullmatch(name)}
    assert covered_by_the_limits_row and {"<PREFIX>CPU_LIMIT", "<PREFIX>MEM_RESERVATION"} <= documented
    documented -= {name for name in documented if name.startswith("<PREFIX>")}

    assert documented == referenced - covered_by_the_limits_row
    assert documented_required == required
    assert required == {"APP_KEY", "APP_URL"} | ({"DB_PASSWORD"} if db != "sqlite" else set()) | (
        {"DB_ROOT_PASSWORD"} if db == "mysql" else set()
    ) | ({"REDIS_PASSWORD"} if queue == "redis" else set())


def _env_example(readme: str) -> str:
    """The minimal env file the README shows under the variable table."""
    section = _section(readme, "### Environment variables")
    return re.search(r"```bash\n(.*?)```", section, re.DOTALL).group(1)


def _compose_config(tmp_path, readme_stack: str, env_file_text: str | None, *args: str, env=None, dot_env=None):
    """``docker compose config`` on ``readme_stack`` with a clean shell, in a directory of its own."""
    if shutil.which("docker") is None or subprocess.run(["docker", "compose", "version"], capture_output=True).returncode:
        pytest.skip("docker compose is not installed")
    for stale in (".env", "deploy.env"):
        (tmp_path / stale).unlink(missing_ok=True)
    (tmp_path / "docker-compose.yml").write_text(readme_stack)
    if dot_env is not None:
        (tmp_path / ".env").write_text(dot_env)
    command = ["docker", "compose"]
    if env_file_text is not None:
        (tmp_path / "deploy.env").write_text(env_file_text)
        command += ["--env-file", "deploy.env"]
    return subprocess.run(
        [*command, "-f", "docker-compose.yml", "config", *args],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env={"PATH": os.environ["PATH"], "HOME": os.environ.get("HOME", "/"), **(env or {})},
    )


@pytest.mark.parametrize("stack", STACKS)
@pytest.mark.parametrize(("db", "queue"), [("mysql", "redis"), ("postgres", "database"), ("sqlite", "sync")])
def test_the_readmes_env_file_is_exactly_what_the_stacks_require(client, tmp_path, stack, db, queue):
    archive = _get_project(client, **_combo(db, queue, False, None))
    example = _env_example(_text(archive, "README.md"))
    compose = _text(archive, stack)

    ok = _compose_config(tmp_path, compose, example)
    assert ok.returncode == 0, ok.stderr

    # Drop any one line and Compose refuses to start: nothing in the example is superfluous.
    lines = example.splitlines()
    assert lines
    for index, line in enumerate(lines):
        without = "\n".join(lines[:index] + lines[index + 1 :])
        result = _compose_config(tmp_path, compose, without)
        assert result.returncode != 0, f"{line.split('=')[0]} is not required, but the README lists it"
        assert "required variable" in result.stderr


@pytest.mark.parametrize("stack", STACKS)
def test_the_readme_describes_how_compose_reads_env_files(client, tmp_path, stack):
    archive = _get_project(client, db="mysql", queue="redis", app_port="9090")
    compose = _text(archive, stack)
    project_env = _text(archive, ".env")
    everything = "APP_KEY=k\nAPP_URL=https://prod.example.com\nDB_PASSWORD=p\nDB_ROOT_PASSWORD=r\nREDIS_PASSWORD=x\n"

    # The generated `.env` is read when no --env-file is given, and its dev values satisfy the guards
    # for APP_KEY, APP_URL and DB_PASSWORD. DB_ROOT_PASSWORD and REDIS_PASSWORD are not in it.
    result = _compose_config(tmp_path, compose, None, dot_env=project_env)
    assert result.returncode != 0
    assert re.search(r"required variable (DB_ROOT_PASSWORD|REDIS_PASSWORD) is missing", result.stderr), result.stderr
    partial = _compose_config(tmp_path, compose, None, dot_env=project_env + "DB_ROOT_PASSWORD=r\nREDIS_PASSWORD=x\n")
    assert partial.returncode == 0, partial.stderr
    assert "APP_URL: http://localhost:9090" in partial.stdout

    # --env-file replaces it rather than adding to it, and the shell wins over both.
    replaced = _compose_config(tmp_path, compose, everything, dot_env=project_env)
    assert "APP_URL: https://prod.example.com" in replaced.stdout
    shell = _compose_config(tmp_path, compose, everything, dot_env=project_env, env={"APP_URL": "https://shell.example.com"})
    assert "APP_URL: https://shell.example.com" in shell.stdout

    # A file with another name is ignored.
    (tmp_path / ".env.prod").write_text(everything)
    ignored = _compose_config(tmp_path, compose, None)
    assert ignored.returncode != 0 and "required variable" in ignored.stderr

    # A `$` stays literal when the value is single-quoted or written `$$`; Compose prints it as `$$`.
    for value in ("'pa$ss'", "pa$$ss"):
        dollar = _compose_config(tmp_path, compose, everything + f"MAIL_PASSWORD={value}\n")
        assert "MAIL_PASSWORD: pa$$ss" in dollar.stdout, value


def test_the_readme_example_command_and_notes_exist(client):
    readme = _text(_get_project(client, db="mysql", queue="redis"), "README.md")
    configuration = _section(readme, "### Configuration")

    for text in (
        "--env-file",
        "silently ignored",
        "named exactly `.env`",
        "`--env-file` replaces the default `.env`",
        "docker compose --env-file .env.prod -f docker-compose.prod.yml config",
        "`exec`, `logs` and `down` included",
        "`$$`",
    ):
        assert text in configuration, text
    assert "`.env.docker`" in configuration  # the example of a file that is not read


# ── The other sections the issue asks for ─────────────────────────────────────


@pytest.mark.parametrize(("queue", "horizon"), QUEUES)
def test_the_staging_and_production_section_covers_what_the_issue_lists(client, queue, horizon):
    readme = _text(_get_project(client, **_combo("sqlite", queue, horizon, "proxy-net", "github")), "README.md")
    section = _section(readme, "## Staging and production")

    assert [line for line in section.splitlines() if line.startswith("### ")] == [
        "### Configuration",
        "### Environment variables",
        "### Deploying",
        "### Commands after a deploy",
        "### Frontend variables (`VITE_*`)",
    ]
    for text in (
        "`demo-stage`",
        "`demo-prod`",
        "[Storage and persistent data](#storage-and-persistent-data)",
        "[Reverse proxy and TLS](#reverse-proxy-and-tls)",
        "[Resource limits](#resource-limits)",
        "[CI pipeline](#ci-pipeline)",
        "`APP_PORT` has no effect",
        "compiled into it",
        "`.env.example`",
        "never put a secret in a `VITE_*` variable",
        "exec -u www-data app php artisan",
        "docker compose -f docker-compose.prod.yml pull",
    ):
        assert text in section, text
    assert ("`WORKER_STOP_GRACE_PERIOD`" in section) == (queue != "sync")
    # The sections it points to are there, and say what the issue wants them to say.
    assert "## Storage and persistent data" in readme and "`sqlite_data`" in readme
    assert "## Reverse proxy and TLS" in readme and "X-Forwarded-Proto" in readme and "`APP_URL`" in readme
    assert "## Resource limits" in readme


def test_the_section_leaves_out_what_the_project_does_not_have(client):
    readme = _text(_get_project(client, db="sqlite", queue="sync"), "README.md")
    section = _section(readme, "## Staging and production")

    assert "CI pipeline" not in section and "docker-publish" not in section
    assert "ci_provider=github" in section  # says how to get one instead
    assert "WORKER_STOP_GRACE_PERIOD" not in readme
    assert "`worker`" not in section and "REDIS_PASSWORD" not in readme and "DB_PASSWORD" not in readme
    assert "Both stacks listen on the host port `APP_PORT`" in section


def test_quick_start_links_the_dashboards_that_are_installed(client):
    both = _text(_get_project(client, queue="redis", horizon="true", telescope="true", app_port="9090"), "README.md")
    neither = _text(_get_project(client, app_port="9090"), "README.md")

    # Hard line breaks (two trailing spaces) keep each URL on its own line.
    assert (
        "App: `http://localhost:9090`  \n"
        "Vite dev server: `http://localhost:5173`  \n"
        "Horizon dashboard: `http://localhost:9090/horizon`  \n"
        "Telescope: `http://localhost:9090/telescope`\n"
    ) in both
    assert "Vite dev server: `http://localhost:5173`\n" in neither
    assert "/horizon" not in neither and "/telescope" not in neither
