name: "Build and Push Docker Image to Docker Hub"

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to use'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-installer:${{ inputs.image_tag }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-installer:${{ inputs.image_tag }}
      - name: Build and Push Nginx Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-laravel-proxy:${{ inputs.image_tag }} -f nginx/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-laravel-proxy:${{ inputs.image_tag }}
