name: "Build and Push Docker Image"

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to use'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/laravel-installer:${{ inputs.image_tag }} ./laravel
          docker push ghcr.io/${{ github.repository_owner }}/laravel-installer:${{ inputs.image_tag }}

      - name: Build and Push Nginx Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nginx-laravel-proxy:${{ inputs.image_tag }} ./nginx
          docker push ghcr.io/${{ github.repository_owner }}/nginx-laravel-proxy:${{ inputs.image_tag }}