name: "Push Stable Docker Image to Docker Hub"

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/docker-build-push-hub.yml
    with:
      image_tag: "stable"
    secrets: inherit
    permissions:
      contents: read
      packages: write